### ISSUE TITLE
Update to Akka 2.4.2

### ISSUE THREAD

**Issue by rrodseth** [maciej/snappy-flows#12]
Type signatures have changed in the Akka 2.4.2 versions of akka streams. 
Thanks.

**Comment by maciej** [comment]
Released 0.1.2. Should be available in Maven central in ~15 minutes.

**Comment by rrodseth** [comment]
Thanks!

**Comment by rrodseth** [comment]
Doesn't seem to be on Maven central yet. Did you forget a step?

**Comment by rrodseth** [comment]
Doesn't seem to be there yet. Thanks again.

**Comment by maciej** [comment]
@rrodseth indeed, I forgot to push the artefacts form bintray. Thank you for reporting that!

**Comment by maciej** [comment]
The new release should be in Maven Central in the next 15-30 minutes.

**Comment by rrodseth** [comment]
@maciej Hmm. Still not seeing it.

**Comment by rrodseth** [comment]
Ah, it's there now.

**Comment by maciej** [comment]
The Bintray -> Maven Central integration is sometimes quite slow. I don't understand why it's not instantaneous, but that's how things are. :-)

**Comment by rrodseth** [comment]
@maciej We're actually having trouble retrieving this artifact using Maven. ArtifactNotFoundException. Possibly a caching issue in our Nexus repository, but if there's anything else you can check...

**Comment by rrodseth** [comment]
@maciej I haven't seen an announcement, but it looks like 2.4.2 (final) is out there now
