### ISSUE TITLE
Update to Akka 2.4.2 Final

### ISSUE THREAD

**Issue by rrodseth** [maciej/snappy-flows#13]
Sadly, there was another change between RC-3 and final. On the decompress side, I get

Caused by: java.lang.ClassNotFoundException: akka.stream.io.ByteStringParser
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

https://github.com/maciej/snappy-flows/issues/12

**Comment by ktoso** [comment]
It's moved to `akka.stream.impl` though it's an internal class; as quickfix you can copy paste it into your codebase I'd say @maciej. We may eventually test it properly and make public again, currently it was an omission that it was public - sorry for the trouble

**Comment by maciej** [comment]
Hey @rrodseth, @ktoso. Thanks for the report and update. I'll look into that tomorrow.

**Comment by maciej** [comment]
Snappy Flows 0.1.3 is now available in Maven Central. It targets Akka 2.4.2 Final.

**Comment by rrodseth** [comment]
@maciej Thanks! Not there yet, but I'll keep an eye out for it.

**Comment by ktoso** [comment]
Great, thanks Maciek :)

**Comment by rrodseth** [comment]
It's there now

**Comment by rrodseth** [comment]
@maciej Sorry to report that 0.1.3 and 2.4.2 are unusable for me. My program, writing 5 files at a time, appears to grind to a halt. Removing the compression step restores the expected performance.
