### ISSUE TITLE
Severe slowdown or deadlock observed with 0.1.3

### ISSUE THREAD

**Issue by rrodseth** [maciej/snappy-flows#15]
@maciej Sorry to report that 0.1.3 and 2.4.2 are unusable for me. My program, writing 5 files at a time, appears to grind to a halt. Removing the compression step restores the expected performance.

**Comment by maciej** [comment]
Does it happen with compression or decompression or both?

**Comment by maciej** [comment]
I've ran the [performance benchmarks](https://github.com/maciej/snappy-flows/tree/master/benchmarks) and they show no slowdown. Neither for compression nor decompression.
Could you try running them on your machine?

**Comment by rrodseth** [comment]
Compression. All I have is via(SnappyFlows.compress()) and if I comment that out, files get created again at high speed. This is running on my OS X laptop, and on one of our servers. In the latter case, I did notice files like snappy-1.1.2-234b20bd-fc78-4781-b416-0a9ebc067d45-libsnappyjava.so. Not sure when those showed up. I might have to set this aside for now, but I'll try to find time to run the benchmarks.

**Comment by maciej** [comment]
What is the input of the `SnappyFlows.compress()` flow?

I'm wondering if the performance degradation is not related only to a certain size of input `ByteString`s.

**Comment by rrodseth** [comment]
They are indeed small. One interval record - three longs and a Double.

```
        val byteStrings: Source[ByteString, akka.NotUsed] = reassembled.map { e =>
          val startTS = e.interval.startTimestamp.getTime
          val endTS = e.interval.endTimestamp.getTime
          val recordedTS = e.interval.recordedTimestamp.getTime
          ByteString(s"${startTS},${endTS},${e.interval.value},${recordedTS}\n")
        }
```

**Comment by rrodseth** [comment]
I think I'm doing the wrong thing to manage the blocking of a mkdirs call. Perhaps related to that, and more aggressive fusing in 2.4.2.?

```
  // Is this the way to manage the blocking mkdirs?
  import scala.concurrent._
  def mkdirs(file: File)(implicit ec: ExecutionContext): Future[(Boolean, Boolean)] = Future {
    blocking {
      val madeDirs = file.getParentFile.mkdirs()
      val created = file.createNewFile()
      (madeDirs, created)
    }
  }

  def writeFile(source: Source[ByteString, akka.NotUsed], file: File)(implicit ec: ExecutionContext, materializer: ActorMaterializer): Future[IOResult] = {
    val result = for {
      madeDirs <- mkdirs(file)
      wroteBytes <- source/*.via(SnappyFlows.compress())*/.runWith(FileIO.toFile(file))
    } yield wroteBytes
    result
  }
```

**Comment by rrodseth** [comment]
You may be right about the ByteString size. 
I changed the above to concatenate ByteStrings and got a bunch of files created fast, but it seems to be stuck on one of them.

```
  def combine(lines:Seq[ByteString]):ByteString = {
    lines.fold(ByteString.empty){ case (acc, e) => acc ++ e }
  }

  def writeFile(source: Source[ByteString, akka.NotUsed], file: File)(implicit ec: ExecutionContext, materializer: ActorMaterializer): Future[IOResult] = {
    val result = for {
      madeDirs <- mkdirs(file)
      wroteBytes <- source.grouped(45000).map(e => combine(e)).via(SnappyFlows.compress()).runWith(FileIO.toFile(file))
    } yield wroteBytes
    result
  }
```

**Comment by rrodseth** [comment]
@maciej Any news from your end?

**Comment by maciej** [comment]
@rrodseth no, not yet. I'm sorry, I haven't had time to look into that today. I'll get back to you tomorrow.

**Comment by rrodseth** [comment]
Thanks!

**Comment by rrodseth** [comment]
@maciej  I take it you haven't had time to look into this further?

**Comment by maciej** [comment]
@rrodseth how many streams are you building in one run?

**Comment by rrodseth** [comment]
@maciej Actually, I _am_ reading the files inside a mapAsync with parallelism 100.

**Comment by rrodseth** [comment]
@maciej My last comment is misleading, since I reported the issue on the write (compress) side. I believe I currently have up to about 125 files writing simultaneously. I've corrected (I think) my handling of the blocking mkdirs call. I wouldn't say the tool runs slowly, but it seems to get stuck after running for a while, when I have compression enabled, but runs reliably without compression enabled. I have threads accessing Slick and also writing to the file system. I don't want to send you on a wild goose chase, unless you think the change you made could have caused concurrency issues.

**Comment by rrodseth** [comment]
@maciej The following prints one ByteString, then hangs. Remove compression and it prints them all.

```
object CompressionTest extends App {

    implicit val system = ActorSystem("Sys")
  implicit val materializer = ActorMaterializer()
  import system.dispatcher

    val countingSink = Sink.fold[Int, Any](0) { case (acc, current) => acc + 1 }

   def randomString(length: Int) = Random.alphanumeric take length mkString("")
   def randomStrings(count: Int, length: Int) = Source(1 to count).map (e => ByteString(randomString(length)))

  val source = randomStrings(count = 10, length = 20).via(SnappyFlows.compress()).map {e => println(e); e}

  val start = Instant.now
  val result = source.runWith(countingSink)
  result.onComplete { e =>
    println(s"Value $e took ${Duration.between(start, Instant.now)}")
    system.shutdown()
  } 
}
```

**Comment by maciej** [comment]
@rrodseth this test case was helpful! Thank you! The issue was relate to chunking. It would fail for short `ByteString`s. I'll release 0.1.4 with a fix for that issue shortly.

**Comment by maciej** [comment]
@rrodseth I've release 0.1.4. It should be available in Maven Central sometime soon.

**Comment by rrodseth** [comment]
@maciej Yay! That fixes the test case I sent, and I have also compressed and decompressed 13K files with my tool.

**Comment by maciej** [comment]
@rrodseth happy to hear that. :-) I'm glad we've managed to cause of identify the issue!
